### ISSUE TITLE
Support for gerrit

### ISSUE THREAD

**Issue by duqcyxwd** [hotoo/gitopen#95]
Any plan to support gerrit?

**Comment by hotoo** [comment]
@duqcyxwd I'm not use gerrit, I donot know gerrit schema path rules.
If you're using gerrit, you can using "custom" type and config like:

```
git.example.com:
  type: custom
  protocol: http
  scheme:
    issues: /path/to/issues
    wiki: /path/to/wikis

    ...
```
more scheme config [reference to github scheme](https://github.com/hotoo/gitopen/blob/master/lib/scheme/github.js)
